export enum OtpVerificationResultReason {
  OTP_EXPIRED_OR_NOT_FOUND = "OTP_EXPIRED_OR_NOT_FOUND",
  OTP_IP_MISMATCH = "OTP_IP_MISMATCH",
  OTP_INCORRECT = "OTP_INCORRECT",
  OTP_VALID = "OTP_VALID"
}